In [12]:
import numpy as np
x = np.arange(1,21,1)
print(x)
x = x.reshape((4,5))
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
s = np.argmax(x, axis=1)
print(s)

[4]
